package goent

import (
	"context"
	"fmt"
	"iter"
	"reflect"

	"github.com/azhai/goent/model"
)

// Entity is the interface for entities that have an ID.
type Entity interface {
	GetID() int64
	SetID(int64)
}

// GenUpdatePairs is an interface for models that can generate update pairs.
// It is typically implemented by code generated by goent-gen.
type GenUpdatePairs interface {
	UpdatePairs() []Pair
	Entity
}

// GenScanDest is an interface for models that can provide scan destinations.
// It is typically implemented by code generated by goent-gen.
type GenScanDest interface {
	ScanDest() []any
}

// GenSetForeign is an interface for models that can set foreign relationship fields
// without reflection. It is typically implemented by code generated by goent-gen.
// When available, QueryForeignByName uses this interface instead of reflect.Value.Set.
type GenSetForeign interface {
	SetForeign(name string, value any)
}

// GenInsertValues is an interface for models that can provide insert values without reflection.
// It is typically implemented by code generated by goent-gen.
// When available, StateInsert.All uses this interface instead of reflect.Value.Field().Interface().
type GenInsertValues interface {
	InsertValues() []any
}

// FetchFunc is a function type that returns a slice of pointers to struct fields for scanning.
type FetchFunc func(target any) []any

// FetchValue returns a slice of pointers to the first field of the target struct.
func FetchValue(target any) []any {
	valueOf := reflect.ValueOf(target).Elem()
	return []any{valueOf.Field(0).Addr().Interface()}
}

// FetchCreator is a function type that creates a FetchFunc based on table info, fields, and foreign.
type FetchCreator func(TableInfo, []*Field, []*Foreign) FetchFunc

// CreateFetchFunc creates a FetchFunc based on the specified fields and foreign relationships.
// It handles both aggregate function results and regular table field scanning.
func CreateFetchFunc(tblInfo *TableInfo, fields []*Field, foreigns []*Foreign) FetchFunc {
	ctx := &fetchContext{tblInfo: tblInfo, fields: fields, foreigns: foreigns}
	if len(fields) > 0 {
		ctx.destSize = len(fields)
	} else {
		ctx.destSize = len(tblInfo.GetSortedFields())
	}
	return func(target any) []any {
		valueOf := reflect.ValueOf(target).Elem()
		if len(fields) > 0 && fields[0].Function != "" {
			return FlattenDest(valueOf)
		}
		if len(fields) > 0 {
			return ctx.buildDest(valueOf)
		}
		dest := AppendDestTable(tblInfo, valueOf)
		for _, foreign := range foreigns {
			dest = append(dest, CreateForeignDest(valueOf, foreign)...)
		}
		return dest
	}
}

// Handler handles database query execution and result processing.
type Handler struct {
	ctx  context.Context
	conn model.Connection
	cfg  *model.DatabaseConfig
}

// NewHandler creates a new Handler with the given context, connection, and database config.
func NewHandler(ctx context.Context, conn model.Connection, cfg *model.DatabaseConfig) *Handler {
	return &Handler{ctx: ctx, conn: conn, cfg: cfg}
}

// ExecuteReturning executes a query with RETURNING clause and scans the result into the specified field.
// It is used for INSERT statements that return auto-generated values like IDs.
//
// Example:
//
//	err := hd.ExecuteReturning(query, valueOf, returnFid)
//	if err != nil {
//		return err
//	}
//	fmt.Println(valueOf.Field(returnFid).Int()) // printed generated ID
func (h *Handler) ExecuteReturning(query model.Query, valueOf reflect.Value, returnFid int) error {
	row, err := query.WrapQueryRow(h.ctx, h.conn, h.cfg)
	if err != nil {
		return err
	}
	fieldOf := valueOf.Field(returnFid)
	query.Err = row.Scan(fieldOf.Addr().Interface())
	if query.Err != nil {
		return h.cfg.ErrorQueryHandler(h.ctx, query)
	}
	return nil
}

// BatchReturning executes a query with RETURNING clause for batch inserts.
// It scans multiple returned rows into successive elements of the slice.
//
// Example:
//
//	err := hd.BatchReturning(query, valueOf, returnFid)
//	if err != nil {
//		return err
//	}
//	fmt.Println(valueOf.Len()) // number of inserted records
func (h *Handler) BatchReturning(query model.Query, valueOf reflect.Value, returnFid int) error {
	rows, err := query.WrapQuery(h.ctx, h.conn, h.cfg)
	if err != nil || rows == nil {
		return err
	}
	defer rows.Close()

	i := 0
	for rows.Next() {
		elem := valueOf.Index(i)
		if elem.Kind() == reflect.Pointer {
			elem = elem.Elem()
		}
		fieldOf := elem.Field(returnFid)
		query.Err = rows.Scan(fieldOf.Addr().Interface())
		if query.Err != nil {
			return h.cfg.ErrorQueryHandler(h.ctx, query)
		}
		i++
	}
	return nil
}

// FetchResult returns an iterator that yields typed results from the query result set.
// This is memory-efficient for processing large result sets.
//
// Example:
//
//	for user, err := range FetchResult[User](hd, query, FetchValue) {
//		if err != nil {
//			return err
//		}
//		fmt.Println(user.Name)
//	}
func FetchResult[R any](hd *Handler, query model.Query, to FetchFunc) iter.Seq2[*R, error] {
	rows, err := query.WrapQuery(hd.ctx, hd.conn, hd.cfg)
	if err != nil || rows == nil {
		return func(yield func(*R, error) bool) {
			yield(nil, err)
		}
	}

	return func(yield func(*R, error) bool) {
		defer rows.Close()
		for rows.Next() {
			target := new(R)
			query.Err = rows.Scan(to(target)...)
			if query.Err != nil {
				yield(target, hd.cfg.ErrorQueryHandler(hd.ctx, query))
				return
			}
			if !yield(target, nil) {
				return
			}
		}
		if err := rows.Err(); err != nil {
			yield(nil, err)
		}
	}
}

type fieldScanInfo struct {
	fieldId    int
	tableAddr  uintptr
	isWildcard bool
}

// fieldDestInfo holds precomputed field destination info for buildDest.
// It caches the field ID, table address, and classification flags
// so that buildDest can avoid repeated field lookups per row.
type fieldDestInfo struct {
	fieldId    int     // Field index in the struct
	tableAddr  uintptr // Table address this field belongs to
	isWildcard bool    // Whether this is a "*" column selector
	isMain     bool    // Whether this field belongs to the main table
	mountIdx   int     // Mount index for foreign fields (0 = not foreign)
}

// fetchContext holds precomputed context for fetching and scanning query results.
// It caches field scan info, destination info, and foreign key offsets
// to minimize reflection overhead during row scanning.
type fetchContext struct {
	tblInfo        *TableInfo
	fields         []*Field
	foreigns       []*Foreign
	scanInfos      []fieldScanInfo
	destInfos      []fieldDestInfo
	destSize       int
	foreignOffsets []foreignOffset
	mainTableAddr  uintptr
}

type foreignOffset struct {
	mountIdx     int
	elemType     reflect.Type
	foreignTable uintptr
}

func (ctx *fetchContext) initForeignOffsets(valueType reflect.Type) {
	if len(ctx.foreignOffsets) > 0 {
		return
	}
	ctx.foreignOffsets = make([]foreignOffset, len(ctx.foreigns))
	for i := range ctx.foreigns {
		sf, ok := valueType.FieldByName(ctx.foreigns[i].MountField)
		if !ok || sf.Type.Kind() == reflect.Slice {
			continue
		}
		ctx.foreignOffsets[i] = foreignOffset{
			mountIdx:     sf.Index[0],
			elemType:     sf.Type.Elem(),
			foreignTable: 0,
		}
		frnInfo := GetTableInfo(ctx.foreigns[i].Reference.TableAddr)
		if frnInfo != nil {
			ctx.foreignOffsets[i].foreignTable = frnInfo.TableAddr
		}
	}
}

func (ctx *fetchContext) initDestInfos() {
	if len(ctx.destInfos) > 0 {
		return
	}
	if len(ctx.fields) > 0 {
		ctx.mainTableAddr = ctx.fields[0].TableAddr
	}
	ctx.destInfos = make([]fieldDestInfo, len(ctx.fields))
	for i, fld := range ctx.fields {
		ctx.destInfos[i] = fieldDestInfo{
			fieldId:    fld.FieldId,
			tableAddr:  fld.TableAddr,
			isWildcard: fld.ColumnName == "*",
			isMain:     fld.TableAddr == ctx.mainTableAddr && fld.TableAddr != 0,
		}
		for _, fo := range ctx.foreignOffsets {
			if fo.foreignTable == fld.TableAddr && fo.foreignTable != 0 {
				ctx.destInfos[i].mountIdx = fo.mountIdx
				break
			}
		}
	}
}

func (ctx *fetchContext) buildDest(valueOf reflect.Value) []any {
	dest := make([]any, 0, ctx.destSize)
	foreignValues := make(map[uintptr]reflect.Value, len(ctx.foreigns))
	ctx.initForeignOffsets(valueOf.Type())
	ctx.initDestInfos()
	for i := range ctx.foreigns {
		fo := ctx.foreignOffsets[i]
		if fo.elemType == nil {
			continue
		}
		foreignValue := reflect.New(fo.elemType)
		valueOf.Field(fo.mountIdx).Set(foreignValue)
		if fo.foreignTable != 0 {
			foreignValues[fo.foreignTable] = foreignValue
		}
	}
	var dummy any
	for _, di := range ctx.destInfos {
		if di.isWildcard {
			if info := GetTableInfo(di.tableAddr); info != nil {
				dest = append(dest, AppendDestTable(info, valueOf)...)
			}
		} else if !di.isMain && di.tableAddr != 0 {
			if fv, ok := foreignValues[di.tableAddr]; ok {
				fieldOf := fv.Elem().Field(di.fieldId)
				dest = append(dest, fieldOf.Addr().Interface())
			} else {
				dest = append(dest, &dummy)
			}
		} else if di.isMain {
			if di.fieldId >= valueOf.NumField() {
				panic(fmt.Sprintf("goent: buildDest field index out of range: fieldId=%d, numFields=%d, type=%s, tableName=%s, mainTableAddr=%d, fieldTableAddr=%d",
					di.fieldId, valueOf.NumField(), valueOf.Type().Name(), ctx.tblInfo.TableName, ctx.mainTableAddr, di.tableAddr))
			}
			fieldOf := valueOf.Field(di.fieldId)
			dest = append(dest, fieldOf.Addr().Interface())
		}
	}
	return dest
}

// CreateForeignDest creates destination pointers for foreign key relationship fields.
// It initializes the related struct field and returns pointers to its columns for scanning.
func CreateForeignDest(valueOf reflect.Value, foreign *Foreign) []any {
	frnInfo := GetTableInfo(foreign.Reference.TableAddr)
	fieldOf := valueOf.FieldByName(foreign.MountField)
	if !fieldOf.IsValid() {
		return nil
	}
	if fieldOf.Kind() == reflect.Pointer && fieldOf.IsNil() {
		fieldOf.Set(reflect.New(fieldOf.Type().Elem()))
	}
	if fieldOf.Kind() == reflect.Pointer {
		if dest, ok := fieldOf.Interface().(GenScanDest); ok {
			return dest.ScanDest()
		}
		return AppendDestTable(frnInfo, fieldOf.Elem())
	}
	return nil
}

// AppendDestTable returns a slice of pointers to the fields of a struct
func AppendDestTable(info *TableInfo, valueOf reflect.Value) []any {
	if dest, ok := valueOf.Addr().Interface().(GenScanDest); ok {
		return dest.ScanDest()
	}
	fields := info.GetSortedFields()
	dest := make([]any, len(fields))
	for i, fld := range fields {
		fieldOf := valueOf.Field(fld.FieldId)
		dest[i] = fieldOf.Addr().Interface()
	}
	return dest
}

// FlattenDest returns a slice of pointers to the fields of a struct
func FlattenDest(valueOf reflect.Value) []any {
	var dest []any
	valueType := valueOf.Type()
	for i := range valueOf.NumField() {
		if geoTag := valueType.Field(i).Tag.Get("goe"); geoTag == "-" {
			continue
		}
		fieldOf := valueOf.Field(i)
		if fieldOf.Kind() == reflect.Slice {
			continue
		}
		if fieldOf.Kind() == reflect.Pointer && fieldOf.Elem().Kind() == reflect.Struct {
			continue
		}
		dest = append(dest, fieldOf.Addr().Interface())
	}
	return dest
}

// }
