package main

import (
	"bytes"
	"cmp"
	"fmt"
	"strings"

	"github.com/azhai/goent/utils"
)

func GenerateConnFile(buf *bytes.Buffer, pkgName, schemaName, dbType, filterPrefix string) error {
	fmt.Fprintf(buf, "//go:build !ignore_autogenerated\n\n")
	tpl := "//go:generate goent-gen tables --dsn $GOE_DATABASE_DSN --schema '%s' --prefix '%s' --force ./\n"
	fmt.Fprintf(buf, tpl, schemaName, filterPrefix)
	fmt.Fprintf(buf, "//go:generate goent-gen fields --force ./\n\n")
	fmt.Fprintf(buf, "package %s\n\n", pkgName)

	importPkgs := utils.NewImports()
	importPkgs.AddThirdPackage("\"github.com/azhai/goent\"")
	if dbType == "pgsql" {
		importPkgs.AddThirdPackage("\"github.com/azhai/goent/drivers/pgsql\"")
	} else {
		importPkgs.AddThirdPackage("\"github.com/azhai/goent/drivers/sqlite\"")
	}
	importPkgs.WriteTo(buf)
	prefix := cmp.Or(filterPrefix, extractCommonPrefix())
	schemaStructName := utils.ToCamelCase(schemaName) + "Schema"

	schemaTag := ""
	if schemaName != "" || prefix != "" {
		parts := make([]string, 0, 2)
		if schemaName != "" {
			parts = append(parts, schemaName)
		}
		if prefix != "" {
			parts = append(parts, fmt.Sprintf("prefix:%s", prefix))
		}
		schemaTag = fmt.Sprintf(" `goe:\"%s\"`", strings.Join(parts, ";"))
	}

	fmt.Fprintf(buf, "// Database represents the database connection.\n")
	fmt.Fprintf(buf, "type Database struct {\n")
	fmt.Fprintf(buf, "\t// %s%s\n", schemaStructName, schemaTag)
	fmt.Fprintf(buf, "\t*goent.DB\n")
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "// Connect opens a database connection.\n")
	fmt.Fprintf(buf, "func Connect(dbDSN, logFile string) (*Database, error) {\n")
	fmt.Fprintf(buf, "\treturn goent.Open[Database](%s.OpenDSN(dbDSN), logFile)\n", dbType)
	fmt.Fprintf(buf, "}\n\n")

	return nil
}
