package main

import (
	"bytes"
	"cmp"
	"fmt"
	"strings"

	"github.com/azhai/goent/reverse"
	"github.com/azhai/goent/utils"
)

var allTables = utils.NewCoMap[string, reverse.TableInfo]()

// RunTablesGeneration generates the tables.go file from database schema
func RunTablesGeneration(cfg *reverse.ReverseConfig, outPath string) error {
	var (
		err error
		eng *reverse.ReverseEngineer
	)
	cfg.Unquote() // remove quotes from config words
	// fmt.Printf("ReverseConfig: %+v\n", cfg)

	if strings.HasPrefix(cfg.DatabaseDSN, "postgres://") {
		eng, err = reverse.NewPgsqlReverseEngineer(cfg.DatabaseDSN, cfg.SchemaName)
	} else {
		eng, err = reverse.NewSqliteReverseEngineer(cfg.DatabaseDSN)
	}
	if err != nil {
		fmt.Println(err)
		return err
	}
	defer eng.Close()

	if initCallback := eng.GetDatabaseConfig().InitCallback(); initCallback != nil {
		if err := initCallback(); err != nil {
			return fmt.Errorf("failed to initialize database: %w", err)
		}
	}

	tableNames, err := eng.GetTables(cfg.TablePrefix)
	if err != nil {
		return fmt.Errorf("failed to get tables: %w", err)
	}

	for _, tableName := range tableNames {
		info, err := eng.GetTableInfo(tableName)
		if err != nil {
			return fmt.Errorf("failed to get table info for %s: %w", tableName, err)
		}
		allTables.Set(tableName, info)
	}

	dbType := "pgsql"
	if strings.Contains(cfg.DatabaseDSN, "sqlite") {
		dbType = "sqlite"
	}

	pkgName := "models"
	if cfg.SchemaName == "" {
		cfg.SchemaName = "public"
	}

	var buf bytes.Buffer
	// _ = GenerateConnFile(&buf, pkgName, config.SchemaName, dbType, config.TablePrefix)

	if err := GenerateModelsFile(&buf, pkgName, cfg.SchemaName, dbType, cfg.TablePrefix); err != nil {
		return err
	}

	if err := utils.WriteToFile(&buf, outPath); err != nil {
		return err
	}

	fmt.Printf("Generated: %s\n", outPath)
	return nil
}

// GenerateModelsFile generates a complete Go file with all models
func GenerateModelsFile(buf *bytes.Buffer, pkgName, schemaName, dbType, filterPrefix string) error {
	fmt.Fprintf(buf, "// Code generated by goent-gen. DO NOT EDIT.\n")
	fmt.Fprintf(buf, "//\n")
	fmt.Fprintf(buf, "//go:build !ignore_autogenerated\n\n")
	fmt.Fprintf(buf, "package %s\n\n", pkgName)

	importPkgs := utils.NewImports()
	importPkgs.AddThirdPackage("\"github.com/azhai/goent\"")

	junctionTables := reverse.FindJunctionTables(allTables)
	complexJunctionTables := reverse.FindComplexJunctionTables(allTables, junctionTables)

	for _, info := range allTables.Each() {
		for _, col := range info.Columns {
			goType := reverse.MapSQLTypeToGo(col.DataType, dbType)
			if goType == "time.Time" {
				importPkgs.AddStdPackage("\"time\"")
			}
			if goType == "uuid.UUID" {
				importPkgs.AddThirdPackage("\"github.com/google/uuid\"")
			}
			if goType == "json.RawMessage" {
				importPkgs.AddStdPackage("\"encoding/json\"")
			}
		}
	}

	importPkgs.WriteTo(buf)
	prefix := cmp.Or(filterPrefix, extractCommonPrefix())
	schemaStructName := utils.ToCamelCase(schemaName) + "Schema"
	fmt.Fprintf(buf, "// %s is the %s schema of the database.\n", schemaStructName, schemaName)
	fmt.Fprintf(buf, "type %s struct {\n", schemaStructName)

	tableNames := allTables.SortedKeys()
	for _, tableName := range tableNames {
		fieldName := utils.ToCamelCase(tableName)
		fieldName = reverse.TrimShortPrefix(fieldName, prefix)
		fieldName = utils.ToSingular(fieldName)
		fmt.Fprintf(buf, "\t%s *goent.Table[%s]\n", fieldName, fieldName)
	}
	fmt.Fprintf(buf, "}\n\n")

	for _, tableName := range tableNames {
		if info, ok := allTables.Get(tableName); ok {
			err := reverse.GenerateModel(buf, info, junctionTables, complexJunctionTables, dbType, prefix)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func extractCommonPrefix() string {
	if allTables.Size() <= 1 {
		return ""
	}

	prefixCounts := make(map[string]int)
	for _, name := range allTables.Keys() {
		for i := 2; i <= len(name); i++ {
			if name[i-1] == '_' {
				prefix := name[:i]
				prefixCounts[prefix]++
			}
		}
	}

	var maxPrefix string
	var maxCount int
	for prefix, count := range prefixCounts {
		if count > maxCount {
			maxCount = count
			maxPrefix = prefix
		}
	}

	if maxCount == 1 {
		return ""
	}

	return maxPrefix
}
