package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"os"
	"path/filepath"

	"golang.org/x/tools/go/packages"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: goent-gen <package-path>")
		fmt.Println("Example: goent-gen ./models")
		os.Exit(1)
	}

	pkgPath := os.Args[1]

	cfg := &packages.Config{
		Mode:  packages.NeedName | packages.NeedFiles | packages.NeedTypes | packages.NeedTypesInfo,
		Tests: false,
	}

	if _, err := os.Stat(pkgPath); err == nil {
		absPath, err := filepath.Abs(pkgPath)
		if err == nil {
			cfg.Dir = absPath
			pkgPath = "."
		}
	}

	pkgs, err := packages.Load(cfg, pkgPath)
	if err != nil {
		fmt.Printf("Error loading package: %v\n", err)
		os.Exit(1)
	}

	if len(pkgs) == 0 {
		fmt.Printf("No packages found at %s\n", pkgPath)
		os.Exit(1)
	}

	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			for _, e := range pkg.Errors {
				fmt.Printf("Package error: %v\n", e)
			}
			continue
		}
		generateForPackage(pkg)
	}
}

// generateForPackage generates the fields.go file for a package.
func generateForPackage(pkg *packages.Package) {
	if len(pkg.GoFiles) == 0 {
		fmt.Printf("No Go files found for package %s\n", pkg.Name)
		return
	}

	structs := filterModels(findStructs(pkg.Types.Scope()), pkg.Name)
	if len(structs) == 0 {
		fmt.Printf("No models found in package %s\n", pkg.Name)
		return
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by goent-gen. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "//\n")
	fmt.Fprintf(&buf, "//go:build !ignore_autogenerated\n")
	fmt.Fprintf(&buf, "// +build !ignore_autogenerated\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg.Name)
	fmt.Fprintf(&buf, "import \"github.com/azhai/goent\"\n\n")

	success := false
	for _, st := range structs {
		if generateStructScanner(&buf, st) {
			success = true
		}
	}
	if !success || buf.Len() == 0 {
		return
	}

	outputPath := filepath.Join(filepath.Dir(pkg.GoFiles[0]), "fields.go")
	if err := writeToFile(&buf, outputPath); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	fmt.Printf("Generated: %s\n", outputPath)
}

func findStructs(scope *types.Scope) []*ModelStruct {
	var structs []*ModelStruct
	for _, name := range scope.Names() {
		obj := scope.Lookup(name)
		if obj == nil {
			continue
		}

		typ, ok := obj.Type().(*types.Named)
		if !ok {
			continue
		}

		st, ok := typ.Underlying().(*types.Struct)
		if !ok || st.NumFields() == 0 {
			continue
		}

		structs = append(structs, &ModelStruct{Name: name, Struct: st, named: typ})
	}
	return structs
}

func writeToFile(buf *bytes.Buffer, path string) error {
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("error formatting output: %w", err)
	}

	if err := os.WriteFile(path, formatted, 0644); err != nil {
		return fmt.Errorf("error writing file: %w", err)
	}
	return nil
}
