package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: goent-gen <package-path>")
		fmt.Println("Example: goent-gen ./models")
		os.Exit(1)
	}

	pkgPath := os.Args[1]

	cfg := &packages.Config{
		Mode:  packages.NeedName | packages.NeedFiles | packages.NeedTypes | packages.NeedTypesInfo,
		Tests: false,
	}

	if _, err := os.Stat(pkgPath); err == nil {
		absPath, err := filepath.Abs(pkgPath)
		if err == nil {
			cfg.Dir = absPath
			pkgPath = "."
		}
	}

	pkgs, err := packages.Load(cfg, pkgPath)
	if err != nil {
		fmt.Printf("Error loading package: %v\n", err)
		os.Exit(1)
	}

	if len(pkgs) == 0 {
		fmt.Printf("No packages found at %s\n", pkgPath)
		os.Exit(1)
	}

	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			for _, e := range pkg.Errors {
				fmt.Printf("Package error: %v\n", e)
			}
			continue
		}
		generateForPackage(pkg)
	}
}

func generateForPackage(pkg *packages.Package) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by goent-gen. DO NOT EDIT.\n")
	buf.WriteString("//\n")
	buf.WriteString("//go:build !ignore_autogenerated\n")
	buf.WriteString("// +build !ignore_autogenerated\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkg.Name))
	buf.WriteString("import \"github.com/azhai/goent\"\n\n")

	scope := pkg.Types.Scope()
	for _, name := range scope.Names() {
		obj := scope.Lookup(name)
		if obj == nil {
			continue
		}

		typ, ok := obj.Type().(*types.Named)
		if !ok {
			continue
		}

		structType, ok := typ.Underlying().(*types.Struct)
		if !ok {
			continue
		}

		if !hasGoentTag(structType) {
			continue
		}

		generateStructScanner(&buf, name, structType)
	}

	if buf.Len() == 0 {
		return
	}

	if len(pkg.GoFiles) == 0 {
		fmt.Printf("No Go files found for package %s\n", pkg.Name)
		return
	}

	outputPath := filepath.Join(filepath.Dir(pkg.GoFiles[0]), "goent_gen.go")
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Printf("Error formatting output: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		fmt.Printf("Error writing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated: %s\n", outputPath)
}

func hasGoentTag(structType *types.Struct) bool {
	for i := 0; i < structType.NumFields(); i++ {
		field := structType.Field(i)
		if field.Embedded() {
			continue
		}
		tag := reflect.StructTag(structType.Tag(i))
		if goeTag := tag.Get("goe"); goeTag != "" && goeTag != "-" {
			return true
		}
	}
	return false
}

func generateStructScanner(buf *bytes.Buffer, typeName string, structType *types.Struct) {
	var fields []struct {
		name string
		typ  string
	}

	for i := 0; i < structType.NumFields(); i++ {
		field := structType.Field(i)
		if !field.Exported() {
			continue
		}

		tag := reflect.StructTag(structType.Tag(i))
		if goeTag := tag.Get("goe"); goeTag == "-" {
			continue
		}

		if field.Embedded() {
			continue
		}

		fieldType := field.Type().String()
		if strings.HasPrefix(fieldType, "[]") {
			continue
		}

		if strings.HasPrefix(fieldType, "*") && isStructType(field.Type()) {
			continue
		}

		fields = append(fields, struct {
			name string
			typ  string
		}{
			name: field.Name(),
			typ:  fieldType,
		})
	}

	if len(fields) == 0 {
		return
	}

	buf.WriteString(fmt.Sprintf("// ScanFields returns a slice of pointers to %s fields for database scanning.\n", typeName))
	buf.WriteString(fmt.Sprintf("func (t *%s) ScanFields() []any {\n", typeName))
	buf.WriteString("\treturn []any{\n")
	for _, f := range fields {
		buf.WriteString(fmt.Sprintf("\t\t&t.%s,\n", f.name))
	}
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("// New%s creates a new %s with pre-allocated scan fields.\n", typeName, typeName))
	buf.WriteString(fmt.Sprintf("func New%s() *%s {\n", typeName, typeName))
	buf.WriteString(fmt.Sprintf("\treturn &%s{}\n", typeName))
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("// Fetch%s creates a FetchFunc for %s.\n", typeName, typeName))
	buf.WriteString(fmt.Sprintf("func Fetch%s() goent.FetchFunc {\n", typeName))
	buf.WriteString("\treturn func(target any) []any {\n")
	buf.WriteString(fmt.Sprintf("\t\treturn target.(*%s).ScanFields()\n", typeName))
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")
}

func isStructType(typ types.Type) bool {
	named, ok := typ.(*types.Named)
	if !ok {
		return false
	}
	_, ok = named.Underlying().(*types.Struct)
	return ok
}
