//go:build !ignore_autogenerated

//go:generate goent-gen tables --dsn $GOE_DATABASE_DSN --schema 'public' --prefix '' --force ./
//go:generate goent-gen fields --force ./

package models

import (
	"github.com/azhai/goent"
	"github.com/azhai/goent/drivers/pgsql"
)

// Database represents the database connection.
type Database struct {
	// PublicSchema `goe:"public"`
	*goent.DB
}

// Connect opens a database connection.
func Connect(dbDSN, logFile string) (*Database, error) {
	return goent.Open[Database](pgsql.OpenDSN(dbDSN), logFile)
}
