// Code generated by goent-gen. DO NOT EDIT.
//
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package models

import "github.com/azhai/goent"

// ------------------------------
// Category
// ------------------------------

// implement goent.Entity interface GetID for Category
func (t *Category) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Category
func (t *Category) SetID(id int64) {
	t.ID = id
}

// ScanFields returns a slice of pointers to Category fields for database scanning.
func (t *Category) ScanFields() []any {
	return []any{
		&t.ID,
		&t.Name,
	}
}

// FetchCategory creates a FetchFunc for Category.
func FetchCategory() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Category).ScanFields()
	}
}

// ------------------------------
// Order
// ------------------------------

// implement goent.Entity interface GetID for Order
func (t *Order) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Order
func (t *Order) SetID(id int64) {
	t.ID = id
}

// ScanFields returns a slice of pointers to Order fields for database scanning.
func (t *Order) ScanFields() []any {
	return []any{
		&t.ID,
		&t.OrderNo,
		&t.Customer,
		&t.Total,
		&t.Status,
		&t.Created,
	}
}

// FetchOrder creates a FetchFunc for Order.
func FetchOrder() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Order).ScanFields()
	}
}

// ------------------------------
// OrderDetail
// ------------------------------

// ScanFields returns a slice of pointers to OrderDetail fields for database scanning.
func (t *OrderDetail) ScanFields() []any {
	return []any{
		&t.OrderID,
		&t.ProductID,
		&t.Quantity,
		&t.Price,
		&t.Product,
	}
}

// FetchOrderDetail creates a FetchFunc for OrderDetail.
func FetchOrderDetail() goent.FetchFunc {
	return func(target any) []any {
		return target.(*OrderDetail).ScanFields()
	}
}

// ------------------------------
// Product
// ------------------------------

// implement goent.Entity interface GetID for Product
func (t *Product) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Product
func (t *Product) SetID(id int64) {
	t.ID = id
}

// ScanFields returns a slice of pointers to Product fields for database scanning.
func (t *Product) ScanFields() []any {
	return []any{
		&t.ID,
		&t.CategoryID,
		&t.Name,
		&t.Color,
		&t.Price,
		&t.Category,
	}
}

// FetchProduct creates a FetchFunc for Product.
func FetchProduct() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Product).ScanFields()
	}
}
