// Code generated by goent-gen. DO NOT EDIT.
//
//go:build !ignore_autogenerated

package models

import "github.com/azhai/goent"

// ------------------------------
// Category
// ------------------------------

// implement goent.Entity interface GetID for Category
func (t *Category) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Category
func (t *Category) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Category) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "name", Value: t.Name},
	}
}

// ScanDest returns a slice of pointers to Category fields for database scanning.
func (t *Category) ScanDest() []any {
	return []any{
		&t.ID,
		&t.Name,
	}
}

// FetchCategory creates a FetchFunc for Category.
func FetchCategory() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Category).ScanDest()
	}
}

// ------------------------------
// Order
// ------------------------------

// implement goent.Entity interface GetID for Order
func (t *Order) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Order
func (t *Order) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Order) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "order_no", Value: t.OrderNo},
		{Key: "customer", Value: t.Customer},
		{Key: "total", Value: t.Total},
		{Key: "status", Value: t.Status},
		{Key: "created", Value: t.Created},
	}
}

// ScanDest returns a slice of pointers to Order fields for database scanning.
func (t *Order) ScanDest() []any {
	return []any{
		&t.ID,
		&t.OrderNo,
		&t.Customer,
		&t.Total,
		&t.Status,
		&t.Created,
	}
}

// FetchOrder creates a FetchFunc for Order.
func FetchOrder() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Order).ScanDest()
	}
}

// ------------------------------
// OrderDetail
// ------------------------------

// ScanDest returns a slice of pointers to OrderDetail fields for database scanning.
func (t *OrderDetail) ScanDest() []any {
	return []any{
		&t.OrderID,
		&t.ProductID,
		&t.Quantity,
		&t.Price,
	}
}

// FetchOrderDetail creates a FetchFunc for OrderDetail.
func FetchOrderDetail() goent.FetchFunc {
	return func(target any) []any {
		return target.(*OrderDetail).ScanDest()
	}
}

// ------------------------------
// Product
// ------------------------------

// implement goent.Entity interface GetID for Product
func (t *Product) GetID() int64 {
	return t.ID
}

// implement goent.Entity interface SetID for Product
func (t *Product) SetID(id int64) {
	t.ID = id
}

// UpdatePairs returns a slice of Pair for updating non-primary key fields.
func (t *Product) UpdatePairs() []goent.Pair {
	return []goent.Pair{
		{Key: "category_id", Value: t.CategoryID},
		{Key: "name", Value: t.Name},
		{Key: "color", Value: t.Color},
		{Key: "price", Value: t.Price},
	}
}

// ScanDest returns a slice of pointers to Product fields for database scanning.
func (t *Product) ScanDest() []any {
	return []any{
		&t.ID,
		&t.CategoryID,
		&t.Name,
		&t.Color,
		&t.Price,
	}
}

// FetchProduct creates a FetchFunc for Product.
func FetchProduct() goent.FetchFunc {
	return func(target any) []any {
		return target.(*Product).ScanDest()
	}
}
