// Code generated by goent-gen. DO NOT EDIT.
//
//go:build !ignore_autogenerated

package models

import (
	"time"

	"github.com/azhai/goent"
)

// PublicSchema is the public schema of the database.
type PublicSchema struct {
	Category    *goent.Table[Category]
	Order       *goent.Table[Order]
	OrderDetail *goent.Table[OrderDetail]
	Product     *goent.Table[Product]
}

// Category represents the t_category table
type Category struct {
	ID   int64 `goe:"pk"`
	Name string
}

// TableName returns the database table name
func (*Category) TableName() string {
	return "t_category"
}

// Order represents the t_order table
type Order struct {
	ID       int64  `goe:"pk"`
	OrderNo  string `goe:"unique"`
	Customer string
	Total    float64
	Status   string
	Created  time.Time
	Details  []*OrderDetail `goe:"-"`
}

// TableName returns the database table name
func (*Order) TableName() string {
	return "t_order"
}

// OrderDetail represents the t_order_detail table
type OrderDetail struct {
	OrderID   int64 `goe:"pk;not_incr;m2o"`
	ProductID int64 `goe:"pk;not_incr;o2o"`
	Quantity  int
	Price     float64
	Product   *Product `goe:"-"`
}

// TableName returns the database table name
func (*OrderDetail) TableName() string {
	return "t_order_detail"
}

// Product represents the t_product table
type Product struct {
	ID         int64 `goe:"pk"`
	CategoryID int64 `goe:"m2o"`
	Name       string
	Color      string
	Price      float64
	Category   *Category `goe:"-"`
}

// TableName returns the database table name
func (*Product) TableName() string {
	return "t_product"
}
